### ISSUE TITLE
Peer-to-Peer code review 20th Nov

### ISSUE THREAD

**Issue by Rhelli** [frederico-miranda/article-writing#1]
A well written article and an extremely well chosen (hot) topic. Some thoughts:

- Maybe take some time to introduce what ARIA is at the beginning of the article so the reader is fully onboard with the concepts you later introduce.

- Maybe look a little more and creating some visual finesse in the final layout between the text and diagrams.

- Consider simplifying the article a little more for the average reader (consider how easy the article is to read for the average person). 

- Consider adding in some sub headings to keep the reader on track

- This is indeed a technical article and therefore isn't intended to appeal to people with zero knowledge however, setting out a few key concepts and defining them at the beginning of the article will improve the number of people who can read your article (and therefore, by effect, increase the number of readers and networking opportunities you receive from the article).

Overall, however, an extremely well written article which reads very well. You've chosen an extremely hot topic and from a count, everybody liked it for the topic! Good luck!

**Comment by frederico-miranda** [comment]
I'm addressing the points that have been raised by the issue:

- "Maybe take some time to introduce what ARIA is at the beginning of the article so the reader is fully onboard with the concepts you later introduce."

I can't do that, because I need to make the reader confused just like I was (so that I can undo the misunderstanding later in the article, and make some points while I do that).

- "Maybe look a little more and creating some visual finesse in the final layout between the text and diagrams."

I'll begin writing the CSS stylesheet once I finish the content of the article.

- "Consider adding in some sub headings to keep the reader on track"

The sub headings have been added.

You can read the source code for the latest sketch of the article at the following link:
[Why does custom HTML elements and ARIA matter? (latest sketch)](https://github.com/frederico-miranda/article-writing/blob/custom-html-and-aria/why-custom-elements-and-aria-matters/index.html)
